const CLOSE_TOPSLIDER: string = "CLOSE_TOPSLIDER";
const OPEN_CURTAIN: string = "OPEN_CURTAIN";
const CLOSE_CURTAIN: string = "CLOSE_CURTAIN";




export { CLOSE_TOPSLIDER, OPEN_CURTAIN, CLOSE_CURTAIN }